# how to use:
# conda env create -f ellie-ml-macos-metal.yml
# conda activate ellie-ml
name: ellie-ml
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  # === Base Python ===
  - python=3.10
  - pip>=24.0

  # === Core Scientific Stack ===
  - numpy>=1.23.5,<1.24
  - pandas>=2.0,<2.2
  - scikit-learn>=1.3,<1.5
  - matplotlib>=3.7,<3.9
  - pillow>=10.0,<11.0
  - tqdm>=4.66,<5

  # === TensorFlow Metal Stack ===
  - tensorflow-deps==2.12.0  # Apple’s dependency bundle for TF
  - pip:
      - tensorflow-macos==2.12.0
      - tensorflow-metal==1.0.0
      - keras==2.12.*
      - tensorboard==2.12.*
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-io-gcs-filesystem==0.32.0

      # === Video / Image I/O ===
      - opencv-python-headless==4.10.0.84

      # === Notebooks / Debug ===
      - jupyterlab
      - notebook

  # === Pós-instalação automática ===
  - pip:
      - pip-autoremove
  - post_install:
      - pip uninstall -y jax jaxlib || true
      - pip-autoremove jax jaxlib -y || true