services:
  ellie-watcher:
    build: .
    container_name: ellie-watcher
    restart: unless-stopped
    environment:
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASS: ${MQTT_PASS}
      MQTT_PREFIX: frigate

      FRIGATE_BASE_URL: http://frigate:5000
      CAMERA_NAME: ellie
      TOILET_ZONE: toilet_zone

      # Heuristic for "squat" (fine-tune later)
      SQUAT_SCORE_THRESH: "0.62"
      SQUAT_MIN_DURATION_S: "2.0"
      # window to search for residue after the act
      RESIDUE_CONFIRM_WINDOW_S: "20"
      RESIDUE_MIN_AREA: "140"
      RESIDUE_STATIC_SEC: "2.0"

      SNAPSHOT_FPS: "4"         # sampling rate when Ellie is in the zone
      CHECK_INTERVAL_S: "15"    # residue re-check when poop_present==on
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - /config/ellie-watcher/.env:/app/.env
      - /config/ellie-watcher/logs:/app/logs
    network_mode: host
    # isolate load; optional
    # cpus: 1.0
    # cpu_shares: 128
    # cpuset: "3"
